name: ecommerce_app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State managment
  # https://pub.dev/packages/flutter_bloc/install
  flutter_bloc: ^9.0.0
  # Code generater (mainly used with cubit & retrifit)
  # https://pub.dev/packages/freezed/install
  freezed: ^2.5.7
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  # https://pub.dev/packages/freezed_annotation/install
  freezed_annotation: ^2.4.4
  # For Dependency injection
  # https://pub.dev/packages/get_it/install
  get_it: ^8.0.2
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  # https://pub.dev/packages/json_serializable/install
  json_serializable: ^6.9.0
  # https://pub.dev/packages/json_annotation/install
  json_annotation: ^4.9.0
  # Networking
  # https://pub.dev/packages/dio/install
  dio: ^5.7.0
  # A Dio Client Generator
  # https://pub.dev/packages/retrofit/install
  retrofit: ^4.4.1
  # Retrofit generator
  # https://pub.dev/packages/retrofit_generator/install
  retrofit_generator: ^9.1.5
  # https://pub.dev/packages/pretty_dio_logger/install
  pretty_dio_logger: ^1.4.0
  # Localization
  # https://pub.dev/packages/intl/install
  intl: ^0.19.0
  # https://pub.dev/packages/easy_localization/install
  easy_localization: ^3.0.7
  # Splash Screen
  # https://pub.dev/packages/flutter_native_splash/install
  # flutter_native_splash: ^2.4.3
  # An SVG rendering and widget library for Flutter, which allows painting
  # https://pub.dev/packages/flutter_svg/install
  flutter_svg: ^2.0.15
  # For Adapting screen and Font size
  # https://pub.dev/packages/flutter_screenutil/install
  flutter_screenutil: ^5.9.3
  # Custom dropdown widget allows to add highly customizable dropdown widget in project
  # https://pub.dev/packages/animated_custom_dropdown/install
  # animated_custom_dropdown: ^3.1.1
  # Collection of cool and beautiful text animations
  # https://pub.dev/packages/animated_text_kit/install
  # animated_text_kit: ^4.2.2
  # For fireBase distribution and firebase services
  # https://pub.dev/packages/firebase_core/install
  # firebase_core: ^3.9.0
  # A package provides an easy way to add shimmer effect
  # https://pub.dev/packages/shimmer/install
  # shimmer: ^3.0.0
  # Reading and writing simple key-value pairs
  # https://pub.dev/packages/shared_preferences/install
  shared_preferences: ^2.3.5
  # Provides API to store data in secure storage
  # https://pub.dev/packages/flutter_secure_storage/install
  flutter_secure_storage: ^9.2.4
  # Beautiful animations inspired on Animate.css
  # https://pub.dev/packages/animate_do/install
  animate_do: ^3.3.4
  # Flutter Page Transition Package which is the transition second page
  # https://pub.dev/packages/page_transition/install
  page_transition: ^2.2.1
  # A customised Flutter TextFormField to input international phone number
  # https://pub.dev/packages/intl_phone_field/install
  # intl_phone_field: ^3.2.0
  # Flutter phone input integrated with flutter internationalization
  # https://pub.dev/packages/phone_form_field/install
  phone_form_field: ^10.0.3
  # A Flutter package to use fonts from fonts.google.com.
  # https://pub.dev/packages/google_fonts/install
  # google_fonts: ^6.1.0
  # Fully customizable OTP Entry TextField for flutter, Widget accepts pin of any length.
  # https://pub.dev/packages/flutter_otp_text_field/install
  flutter_otp_text_field: ^1.4.0+2
  # Toast Library for Flutter, Easily create toast messages in single line of code
  # https://pub.dev/packages/fluttertoast/install
  fluttertoast: ^8.2.10
  # Stunning Animating Curved Shape Navigation Bar. Adjustable color, background color, animation curve, animation duration
  # https://pub.dev/packages/curved_navigation_bar/install
  curved_navigation_bar: ^1.0.6
  # A Flutter package with custom implementation of the Side Menu (Drawer)
  # https://pub.dev/packages/flutter_zoom_drawer/install
  flutter_zoom_drawer: ^3.2.0
  # it is made to replace Snackbars and Toasts
  # https://pub.dev/packages/another_flushbar/install
  another_flushbar: ^1.12.30
  # Render After Effects animations natively on Flutter. This package is a pure Dart implementation of a Lottie player
  # https://pub.dev/packages/lotti
  lottie: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/build_runner/install
  build_runner: ^2.4.13
  # https://pub.dev/packages/flutter_gen_runner/install
  flutter_gen_runner: ^5.8.0
  flutter_lints: ^4.0.0

flutter_gen:
  output: lib/core/assets_gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/
    - assets/lottie_animation/

  fonts:
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/play_fair_display/PlayfairDisplay-Italic.ttf
        - asset: assets/fonts/play_fair_display/PlayfairDisplay.ttf
          # style: italic
    - family: AirbnbCerialApp
      fonts:
        - asset: assets/fonts/airbnb_cereal_app/airbnb-cereal-app-medium.ttf
        - asset: assets/fonts/airbnb_cereal_app/airbnb-cereal-app-book.ttf
          # style: italic
    # - family: Poppins
    #   fonts:
    #     - asset: assets/fonts/Poppins-Regular.ttf
    #     - asset: assets/fonts/Poppins-Medium.ttf
    #       weight: 500
    #     - asset: assets/fonts/Poppins-SemiBold.ttf
    #       weight: 600
    #     - asset: assets/fonts/Poppins-Bold.ttf
    #       weight: 700
